### PR TITLE
SocketServer: add listen backlog option

### PR DESCRIPTION
**Pull request by sillyousu**

### CODE REVIEW

**Comment by mgravell** [comment]
I'm absolutely fine with the principle here, but the change *as presented* is not binary compatible, meaning: it would cause a `MissingMethodException` for anyone who is taking the dependency in a transitive way and thus don't recompile directly against the updated API. It will also break anyone who is explicitly passing `null` as the last two arguments.

The usual way of avoiding this problem is to add the extended API as a new overload, i.e. add

``` c#
        /// <summary>
        /// Start listening as a server
        /// </summary>
        public void Listen(
            EndPoint endPoint,
            AddressFamily addressFamily,
            SocketType socketType,
            ProtocolType protocolType,
            PipeOptions sendOptions, PipeOptions receiveOptions)
            => Listen(endPoint, addressFamily, socketType, protocolType, 20, sendOptions, receiveOptions);
```

This retains the old API, avoiding the `MissingMethodException` problem. It still has a *slight* problem in that it will fail if someone is explicitly passing (by position, not name) `null` as `sendOptions` and implicitly `receiveOptions` - since we've juggled the parameter order, this gets a little messy, but... I'm comfortable with it since they're rebuilding anyway. Note that because all the parameters are non-optional, in most cases callers will be pushed directly to the new API automatically when they recompile. Existing callers will continue to use the old API. In some cases it might be worth providing an aggressive inlining hint here, but ... people don't tend to create servers in a tight loop, so I think that would be overkill.

If we think it is *likely* that we'll need to keep adding additional parameters, another option is to create a `ListenOptions` class with *properties* instead of parameters. I don't think we need to go to that level yet here.

**Comment by sillyousu** [comment]
@mgravell  
just updated this PR PTAL.

**Comment by mgravell** [comment]
In the revised version I think you've inverted the optional args; the *optional* args go on the *real version* - the one that actually does the stuff directly. You make the args non-optional on the **old** version - the one that is now just a `=>` forwarded to the *new* method. That way:

- new code/builds goes directly to the "real" method
- old code that explicitly targeted the old overload still works

**Comment by sillyousu** [comment]
@mgravell  please take another look. 
Just learn binary compatibility today. I had never thought of that.

**Comment by sillyousu** [comment]
will send another PR latter.

**Comment by sillyousu** [comment]
what about adding a new `SetListenBacklog` API and keeping `Listen` untouch?

```diff
diff --git a/src/Pipelines.Sockets.Unofficial/SocketServer.cs b/src/Pipelines.Sockets.Unofficial/SocketServer.cs
index 8945a50..30a87d3 100644
--- a/src/Pipelines.Sockets.Unofficial/SocketServer.cs
+++ b/src/Pipelines.Sockets.Unofficial/SocketServer.cs
@@ -13,6 +13,7 @@ namespace Pipelines.Sockets.Unofficial
     public abstract class SocketServer : IDisposable
     {
         private Socket _listener;
+        private int _listenBacklog = 20;

         /// <summary>
         /// Start listening as a server
@@ -27,7 +28,7 @@ namespace Pipelines.Sockets.Unofficial
             if (_listener != null) Throw.InvalidOperation("Server is already running");
             Socket listener = new Socket(addressFamily, socketType, protocolType);
             listener.Bind(endPoint);
-            listener.Listen(20);
+            listener.Listen(_listenBacklog);

             _listener = listener;
             StartOnScheduler(receiveOptions?.ReaderScheduler, _ => FireAndForget(ListenForConnectionsAsync(
@@ -36,6 +37,13 @@ namespace Pipelines.Sockets.Unofficial
             OnStarted(endPoint);
         }

+        public void SetListenBacklog(int backlog)
+        {
+            if (_listener != null) Throw.InvalidOperation("Server is already running");
+            _listenBacklog = backlog;
+        }
+
+
```

**Comment by sillyousu** [comment]
In Golang , I'm used to using `functional-options` idiom.
Not sure what is the best way to provide a public API in C#.

https://github.com/tmrts/go-patterns/blob/master/idiom/functional-options.md#functional-options

**Pull request closed without merging**
