### PR TITLE
remove .NET 4.6 target as a workaround to invalid assemblyBinding redirect generation

### PR DESCRIPTION
**Pull request by adamsitnik**
This PR is a workaround.

Project A targets `netstandard2.0;netcoreapp2.0;netcoreapp2.1;net46`
When project B references A and targets `net46;netcoreapp2.1` everything works fine.
But when we have another project C (generated by BDN in our case) which targets `net46` and references B, the tooling goes crazy and can not generate the right assemblyBinding redirects for System.Buffers.

This workaround removes `net46` target from the `Pipelines.Sockets.Unofficial` and updates all other projects to .NET 4.6.1 which implements .NET Standard 2.0. It looks like tooling  (dotnet cli/nuget/vs) can handle this case.

I am going to create a separate issue in CoreFX.

@mgravell @NickCraver btw when you will be comparing memory allocations for .NET vs .NET Core you need to be aware of https://github.com/dotnet/BenchmarkDotNet/issues/723 long story short: .NET Core exposes the allocated memory with `System.GC.GetAllocatedBytesForCurrentThread()` API, which returns the memory allocated only for **current**  thread. So if benchmark spawns few threads, then for .NET Core we show invalid value ;(

### CODE REVIEW

**Comment by mgravell** [comment]
> So if benchmark spawns few threads, then for .NET Core we show invalid value ;(

That's unfortunate - because of the nature of the thing being tested, threads are unavoidable - this is async socket IO with dispatch to a pool of user threads, etc. Oh well, it is what it is.

> But when we have another project C (generated by BDN in our case) which targets net46 and references B, the tooling goes crazy and can not generate the right assemblyBinding redirects for System.Buffers.

Indeed, I've already seen problems in that area - which is why I had to generate manual app.config files in the first place; when using the inbuilt tooling, it just didn't work - same error.

**Comment by mgravell** [comment]
I guess it isn't a huge loss to move from net46 to net461 (using netstandard2.0); some *minor* vexation, but I think I'll get over it, thanks!

**Comment by NickCraver** [comment]
@adamsitnik thanks for the quick assist here - it's very much appreciated, as is the heads up on the benchmark numbers being off. It's so satisfying to know I'm not the only thing that's crazy sometimes :)

**Comment by adamsitnik** [comment]
> That's unfortunate - because of the nature of the thing being tested, threads are unavoidable - this is async socket IO with dispatch to a pool of user threads, etc. Oh well, it is what it is.

I know ;( I will do my best to fix this issue for .NET Core 2.2

> It's so satisfying to know I'm not the only thing that's crazy sometimes :)

I could not believe my eyes today when I was able to reproduce it ;) 

I reported a bug in CoreFx https://github.com/dotnet/corefx/issues/30642 Hopefully it's going to get fixed and explained

**Pull request merged**
